apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mydeployment
  labels:
    app: mytestserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytestserver
  template:
    metadata:
      labels:
        app: mytestserver
    spec:
      containers:
        - name: mytestserver
          image: thiran228/myapp:v2
          ports:
            - containerPort: 3000
