apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: mytestserver
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30396
  type: NodePort
